services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d docker -U docker"]
      interval: 10s
      timeout: 5s
      retries: 7

  server:
    build: .
    ports:
      - 8080:8080
    depends_on: 
      postgres:
        condition: service_healthy
  